version: "2.4"
services:
  scheduler-api:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://user:pass@postgres:5432/scheduler
      NODE_ENV: development
      PORT: 22223
    ports:
      - "22223:22223"
    command: node ./src/index.js
    restart: on-failure
    volumes:
      - .:/scheduler-api/
      - /scheduler-api/node_modules

  postgres:
    image: postgres:10.4
    ports:
      - "35432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: scheduler
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./src/db/schema/create.sql:/docker-entrypoint-initdb.d/10-schema.sql
      - ./src/db/schema/development.sql:/docker-entrypoint-initdb.d/20-seeds.sql
